require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AuthorizedEmailsController do

  # This should return the minimal set of attributes required to create a valid
  # AuthorizedEmail. As you add validations to AuthorizedEmail, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "email" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AuthorizedEmailsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all authorized_emails as @authorized_emails" do
      authorized_email = AuthorizedEmail.create! valid_attributes
      get :index, {}, valid_session
      assigns(:authorized_emails).should eq([authorized_email])
    end
  end

  describe "GET show" do
    it "assigns the requested authorized_email as @authorized_email" do
      authorized_email = AuthorizedEmail.create! valid_attributes
      get :show, {:id => authorized_email.to_param}, valid_session
      assigns(:authorized_email).should eq(authorized_email)
    end
  end

  describe "GET new" do
    it "assigns a new authorized_email as @authorized_email" do
      get :new, {}, valid_session
      assigns(:authorized_email).should be_a_new(AuthorizedEmail)
    end
  end

  describe "GET edit" do
    it "assigns the requested authorized_email as @authorized_email" do
      authorized_email = AuthorizedEmail.create! valid_attributes
      get :edit, {:id => authorized_email.to_param}, valid_session
      assigns(:authorized_email).should eq(authorized_email)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AuthorizedEmail" do
        expect {
          post :create, {:authorized_email => valid_attributes}, valid_session
        }.to change(AuthorizedEmail, :count).by(1)
      end

      it "assigns a newly created authorized_email as @authorized_email" do
        post :create, {:authorized_email => valid_attributes}, valid_session
        assigns(:authorized_email).should be_a(AuthorizedEmail)
        assigns(:authorized_email).should be_persisted
      end

      it "redirects to the created authorized_email" do
        post :create, {:authorized_email => valid_attributes}, valid_session
        response.should redirect_to(AuthorizedEmail.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved authorized_email as @authorized_email" do
        # Trigger the behavior that occurs when invalid params are submitted
        AuthorizedEmail.any_instance.stub(:save).and_return(false)
        post :create, {:authorized_email => { "email" => "invalid value" }}, valid_session
        assigns(:authorized_email).should be_a_new(AuthorizedEmail)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AuthorizedEmail.any_instance.stub(:save).and_return(false)
        post :create, {:authorized_email => { "email" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested authorized_email" do
        authorized_email = AuthorizedEmail.create! valid_attributes
        # Assuming there are no other authorized_emails in the database, this
        # specifies that the AuthorizedEmail created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AuthorizedEmail.any_instance.should_receive(:update).with({ "email" => "MyString" })
        put :update, {:id => authorized_email.to_param, :authorized_email => { "email" => "MyString" }}, valid_session
      end

      it "assigns the requested authorized_email as @authorized_email" do
        authorized_email = AuthorizedEmail.create! valid_attributes
        put :update, {:id => authorized_email.to_param, :authorized_email => valid_attributes}, valid_session
        assigns(:authorized_email).should eq(authorized_email)
      end

      it "redirects to the authorized_email" do
        authorized_email = AuthorizedEmail.create! valid_attributes
        put :update, {:id => authorized_email.to_param, :authorized_email => valid_attributes}, valid_session
        response.should redirect_to(authorized_email)
      end
    end

    describe "with invalid params" do
      it "assigns the authorized_email as @authorized_email" do
        authorized_email = AuthorizedEmail.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AuthorizedEmail.any_instance.stub(:save).and_return(false)
        put :update, {:id => authorized_email.to_param, :authorized_email => { "email" => "invalid value" }}, valid_session
        assigns(:authorized_email).should eq(authorized_email)
      end

      it "re-renders the 'edit' template" do
        authorized_email = AuthorizedEmail.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AuthorizedEmail.any_instance.stub(:save).and_return(false)
        put :update, {:id => authorized_email.to_param, :authorized_email => { "email" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested authorized_email" do
      authorized_email = AuthorizedEmail.create! valid_attributes
      expect {
        delete :destroy, {:id => authorized_email.to_param}, valid_session
      }.to change(AuthorizedEmail, :count).by(-1)
    end

    it "redirects to the authorized_emails list" do
      authorized_email = AuthorizedEmail.create! valid_attributes
      delete :destroy, {:id => authorized_email.to_param}, valid_session
      response.should redirect_to(authorized_emails_url)
    end
  end

end
