require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EntrySchedulesController do

  # This should return the minimal set of attributes required to create a valid
  # EntrySchedule. As you add validations to EntrySchedule, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EntrySchedulesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all entry_schedules as @entry_schedules" do
      entry_schedule = EntrySchedule.create! valid_attributes
      get :index, {}, valid_session
      assigns(:entry_schedules).should eq([entry_schedule])
    end
  end

  describe "GET show" do
    it "assigns the requested entry_schedule as @entry_schedule" do
      entry_schedule = EntrySchedule.create! valid_attributes
      get :show, {:id => entry_schedule.to_param}, valid_session
      assigns(:entry_schedule).should eq(entry_schedule)
    end
  end

  describe "GET new" do
    it "assigns a new entry_schedule as @entry_schedule" do
      get :new, {}, valid_session
      assigns(:entry_schedule).should be_a_new(EntrySchedule)
    end
  end

  describe "GET edit" do
    it "assigns the requested entry_schedule as @entry_schedule" do
      entry_schedule = EntrySchedule.create! valid_attributes
      get :edit, {:id => entry_schedule.to_param}, valid_session
      assigns(:entry_schedule).should eq(entry_schedule)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new EntrySchedule" do
        expect {
          post :create, {:entry_schedule => valid_attributes}, valid_session
        }.to change(EntrySchedule, :count).by(1)
      end

      it "assigns a newly created entry_schedule as @entry_schedule" do
        post :create, {:entry_schedule => valid_attributes}, valid_session
        assigns(:entry_schedule).should be_a(EntrySchedule)
        assigns(:entry_schedule).should be_persisted
      end

      it "redirects to the created entry_schedule" do
        post :create, {:entry_schedule => valid_attributes}, valid_session
        response.should redirect_to(EntrySchedule.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved entry_schedule as @entry_schedule" do
        # Trigger the behavior that occurs when invalid params are submitted
        EntrySchedule.any_instance.stub(:save).and_return(false)
        post :create, {:entry_schedule => { "name" => "invalid value" }}, valid_session
        assigns(:entry_schedule).should be_a_new(EntrySchedule)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        EntrySchedule.any_instance.stub(:save).and_return(false)
        post :create, {:entry_schedule => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested entry_schedule" do
        entry_schedule = EntrySchedule.create! valid_attributes
        # Assuming there are no other entry_schedules in the database, this
        # specifies that the EntrySchedule created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        EntrySchedule.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => entry_schedule.to_param, :entry_schedule => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested entry_schedule as @entry_schedule" do
        entry_schedule = EntrySchedule.create! valid_attributes
        put :update, {:id => entry_schedule.to_param, :entry_schedule => valid_attributes}, valid_session
        assigns(:entry_schedule).should eq(entry_schedule)
      end

      it "redirects to the entry_schedule" do
        entry_schedule = EntrySchedule.create! valid_attributes
        put :update, {:id => entry_schedule.to_param, :entry_schedule => valid_attributes}, valid_session
        response.should redirect_to(entry_schedule)
      end
    end

    describe "with invalid params" do
      it "assigns the entry_schedule as @entry_schedule" do
        entry_schedule = EntrySchedule.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EntrySchedule.any_instance.stub(:save).and_return(false)
        put :update, {:id => entry_schedule.to_param, :entry_schedule => { "name" => "invalid value" }}, valid_session
        assigns(:entry_schedule).should eq(entry_schedule)
      end

      it "re-renders the 'edit' template" do
        entry_schedule = EntrySchedule.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EntrySchedule.any_instance.stub(:save).and_return(false)
        put :update, {:id => entry_schedule.to_param, :entry_schedule => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested entry_schedule" do
      entry_schedule = EntrySchedule.create! valid_attributes
      expect {
        delete :destroy, {:id => entry_schedule.to_param}, valid_session
      }.to change(EntrySchedule, :count).by(-1)
    end

    it "redirects to the entry_schedules list" do
      entry_schedule = EntrySchedule.create! valid_attributes
      delete :destroy, {:id => entry_schedule.to_param}, valid_session
      response.should redirect_to(entry_schedules_url)
    end
  end

end
